// Each new term in the Fibonacci sequence is generated by adding the previous 
// two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed 
// four million, find the sum of the even-valued terms.

var fib_arr = [1,1]

var limit = 4000000

while(fib_arr[fib_arr.length-1] < limit){
	if (fib_arr[fib_arr.length-1] > 3000000){
		break;
	}
	fib_arr.push(fib_arr[fib_arr.length-1] + fib_arr[fib_arr.length-2]);
}

// console.log(fib_arr); --> USE THIS TO VISUALIZE THE SEQUENCE

var sum_evens=0

for (var i = 0; i<fib_arr.length; i++){
	if(fib_arr[i]%2 === 0){
		sum_evens = sum_evens + fib_arr[i];
	}
}

console.log(sum_evens);